name: Fetch Docker Mangata node

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone mangata node repository
        uses: actions/checkout@v2
        with:
          repository: mangata-finance/mangata-node
          path: mangata-repo
          ref: develop
      - name: Check cloned repo
        run: |
          cd $GITHUB_WORKSPACE/mangata-repo
          ls -a

      - name: Stop previous parachain if running
        run: make -C $GITHUB_WORKSPACE/mangata-repo/devops/parachain stop

      - name: Start mangata-node parachain
        env:
          ENV: rococo
        run: make -C $GITHUB_WORKSPACE/mangata-repo/devops/parachain stop start

      - name: Docker ps
        run: docker ps
