name: Fetch Docker Mangata node

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone mangata node repository
        uses: actions/checkout@v2

      - name: create release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
